version: "3.4"
services:
  dev:
    build:
      context: .
      network: host
      target: app_dev
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    restart: always
  code:
    build:
      context: .
      network: host
      target: code
    volumes:
      - ./app:/app
    ports:
      - "2222:22"
    restart: always
{{#features.jupyter}}
  jupyter:
    build:
      context: .
      network: host
      target: jupyter
    volumes:
      - ./app:/app
      - ./notebooks:/notebooks
    ports:
      - "8888:8888"
    restart: always
{{/features.jupyter}}
